plugins {
    id 'application'
    id 'checkstyle'
}

version = '0.1'

repositories {
    mavenCentral()
}

java {
    toolchain {
        JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'com.silvanschermer.Main'
}

jar {
    manifest {
        attributes(
                'main-class': 'com.silvanschermer.Main'
        )
    }
}

checkstyle {
    toolVersion = '12.0.1'
    config = resources.text.fromUri('https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml')
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

tasks.withType(Checkstyle).configureEach {
    reports {
        xml.required = false
        html.required = true
    }
}